show all avatars
Fluorinebot/fluorine pull request #109
Opened 2022-02-11 22:36 UTC by night-lake

adds the ability to see both the user and guild avatar of a member

2022-02-12 14:13 UTC, xiboon approved these changes, later dismissed

2022-02-12 14:19 UTC, SuperchupuDev requested changes

2022-02-12 14:19 UTC, SuperchupuDev commented on src/components/avatar.ts
> +    const [memberID, action] = value.split('.');
can you rename this to `memberId`?

2022-02-12 14:29 UTC, night-lake commented on src/components/avatar.ts
> +    const [memberID, action] = value.split('.');
ah camelCase and the word ID, never gets old.

2022-02-12 17:52 UTC, xiboon submitted a review, later dismissed

2022-02-12 18:10 UTC, SuperchupuDev requested changes
also remember to add `{ lng: interaction.locale }` to all translations

2022-02-12 18:10 UTC, SuperchupuDev commented on src/commands/avatar.ts
> +    } else if (user) {
user will always be true

2022-02-12 22:04 UTC, Nyameliaaaa commented on src/commands/avatar.ts
> +    } else if (user) {
we're checking if we have a user object BUT that user object isnt a guild member
if true then we show only the user avatar (User objects dont have guild avatars)
if user is false we skip into the show the author block.

2022-02-12 22:55 UTC, SuperchupuDev approved these changes, later dismissed

2022-02-13 11:45 UTC, SuperchupuDev approved these changes

2022-02-13 11:46 UTC, xiboon approved these changes
sent from ur mom

2022-02-13 11:46 UTC, merged