general cleanup
Fluorinebot/fluorine pull request #153
Opened 2022-03-28 17:32 UTC by night-lake

this pr is an extension of #119

2022-03-31 15:57 UTC, xiboon approved these changes

2022-04-12 08:07 UTC, SuperchupuDev commented on src/commands/profile/view.ts
> +    const attachment = new MessageAttachment(canva.toBuffer(), 'profile?.png');
```suggestion
    const attachment = new MessageAttachment(canva.toBuffer(), 'profile.png');
```
its literally the filename lol

2022-04-12 08:07 UTC, SuperchupuDev reviewed
also remove the polish `PROFILE_INVALID_USER` translation too

2022-04-12 14:27 UTC, xiboon commented on src/commands/profile/view.ts
> +    const attachment = new MessageAttachment(canva.toBuffer(), 'profile?.png');
I AGREE

2022-04-17 09:43 UTC, SuperchupuDev requested changes

2022-04-17 09:43 UTC, SuperchupuDev commented on tsconfig.json
> +}
```suggestion
}

```

2022-04-17 11:46 UTC, SuperchupuDev approved these changes

2022-04-17 15:36 UTC, night-lake commented
> also remove the polish `PROFILE_INVALID_USER` translation too

will do when i fix the i18n strings

2022-04-17 15:36 UTC, merged