tags
Fluorinebot/fluorine pull request #81
Opened 2022-01-30 17:44 UTC by night-lake

closes #75

2022-01-31 16:05 UTC, night-lake commented
seems like theres an issue with raw exporting

2022-02-02 08:59 UTC, night-lake commented
alright so all thats missing is:

@xiboon -----
rethink for delete in `components/tagDelete`
rethink for tags list

not assigned ------
fixing the command deleter in `components/tagDelete`
proper date in `tags/list`
paginator for tags list

2022-02-03 22:54 UTC, SuperchupuDev requested changes

2022-02-03 22:54 UTC, SuperchupuDev commented on i18n/en-US.json
> +    "8BALL_RESPONSES": [
```suggestion
    "8BALL_RESPONSES": [
```

2022-02-03 22:54 UTC, SuperchupuDev commented on i18n/en-US.json
> +    "MONTHS": [
```suggestion
    "MONTHS": [
```

2022-02-06 15:13 UTC, xiboon approved these changes, later dismissed

2022-02-06 20:49 UTC, night-lake commented on src/classes/Client.ts
> +
```suggestion
import PhishingHandler from './handlers/PhishingHandler';
```

2022-02-06 21:26 UTC, SuperchupuDev requested changes
have fun

2022-02-06 21:26 UTC, SuperchupuDev commented on src/classes/handlers/TagHandler.ts
> +                    }
```suggestion
                    const cleanParams = params.map(param => this.getParsedStaticVars(
                        param.replaceAll('--', ' '),
                        '$',
                        '$',
                        interaction
                    ));
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/commands/tags/index.ts
> +export const dev = true;
```suggestion
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/commands/tags/raw.ts
> +    const guildCommands = _guildCommands.map(x => x[1].name);
```suggestion
    const guildCommands = (await interaction.guild.commands.fetch()).map(c => c.name)
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/components/tagDelete.ts
> +    // @ts-ignore
```suggestion
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/components/tagList.ts
> +        if (!resultArray[chunkIndex]) resultArray[chunkIndex] = [];
```suggestion
        resultArray[chunkIndex] ||= [];
```
can't be `??=` because that checks for `null` and `undefined`, not `NaN`

2022-02-06 21:26 UTC, SuperchupuDev commented on src/components/tagList.ts
> +    );
```suggestion
    const row = new MessageActionRow()
        .addComponents(
            new MessageButton()
                .setCustomId(`tagsList:${interaction.user.id}:${page - 1}`)
                .setLabel(
                    client.i18n.t('LISTCASE_BACK', { lng: interaction.locale })
                )
                .setStyle('PRIMARY')
                .setDisabled(page === 0),
            new MessageButton()
                .setCustomId(`tagsList:${interaction.user.id}:${page + 1}`)
                .setLabel(
                    client.i18n.t('LISTCASE_NEXT', { lng: interaction.locale })
                )
                .setStyle('PRIMARY')
                .setDisabled(page + 1 === chunk.length)
    );
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/components/tagList.ts
> +    );
```suggestion
    const embed = new Embed(client, interaction.locale)
        .setLocaleTitle('TAGS_LIST_TITLE', { server: interaction.guild.name });
        .setDescription(
            codeBlock(
                'yaml',
                chunk[0]
                    .map(x => x.name.replace(`${interaction.guild.id}-`, ''))
                    .join(', ')
            )
        );
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/classes/handlers/TagHandler.ts
> +                    const user = this.client.users.cache.get(params[0]);
```suggestion
                user: async (interaction: CommandInteraction, params: string[]) => {
                    const user = await this.client.users.fetch(params[0]);
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/classes/handlers/TagHandler.ts
> +    }
```suggestion
    splitForActions(content: string): string[] {
        return content.split(/[{}]/);
    }
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/classes/handlers/TagHandler.ts
> +        const [tagContent, tagEmbed] = tagString.split('@embed');
```suggestion
        const [tagContent] = tagString.split('@embed');
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/commands/tags/create.ts
> +    if (guildCommands.includes(name))
```suggestion
    const guildCommands = await interaction.guild.commands.fetch();

    if (fluorineCommands.includes(name))
        return interaction.reply({
            content: client.i18n.t('TAGS_CREATE_FLUORINE_OVERRIDE', {
                lng: interaction.locale
            }),
            ephemeral: true
        });

    if (guildCommands.size >= 100) {
        return interaction.reply({
            content: client.i18n.t('TAGS_CREATE_MAXIMUM', {
                lng: interaction.locale
            }),
            ephemeral: true
        });
    }

    if (guildCommands.has(name))
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/commands/tags/delete.ts
> +    ]);
```suggestion
    const [tag] = (await r
        .table('tags')
        .getAll([interaction.guild.id, name], { index: 'tag' })
        .coerceTo('array')
        .run(client.conn)) as Tag[];

    if (!tag)
        return interaction.reply({
            content: client.i18n.t('TAG_DOESNT_EXIST', {
                lng: interaction.locale
            }),
            ephemeral: true
        });

    if (!interaction.memberPermissions.has('MANAGE_GUILD'))
        return interaction.reply({
            content: client.i18n.t('TAGS_DELETE_NOT_TAG_OWNER', {
                lng: interaction.locale
            }),
            ephemeral: true
        });

    const row = new MessageActionRow()
        addComponents([
            new MessageButton()
                .setCustomId(`tagDelete:${interaction.user.id}:yes.${name}`)
                .setLabel(
                    client.i18n.t('TAGS_DELETE_CONTINUE', {
                        lng: interaction.locale
                    })
                )
                .setStyle(MessageButtonStyles.DANGER),
            new MessageButton()
                .setCustomId(`tagDelete:${interaction.user.id}:no.${name}`)
                .setLabel(
                    client.i18n.t('TAGS_DELETE_EXIT', {
                        lng: interaction.locale
                    })
                )
                .setStyle(MessageButtonStyles.SUCCESS)
        ]);
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/commands/tags/list.ts
> +        const guildCommands = _guildCommands.map(x => x[1].name);
```suggestion
        const guildCommands = (await interaction.guild.commands.fetch()).map(c => c.name);
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/commands/tags/list.ts
> +        });
```suggestion
        const embed = new Embed(client, interaction.locale)
            .setLocaleTitle('TAGS_LIST_SPECIFIC_TITLE')
            .addLocaleField({
                name: 'TAGS_LIST_SPECIFIC_USER',
                value: client.users.cache.get(tag.user).toString()
            })
            .addLocaleField({
                name: 'TAGS_LIST_SPECIFIC_DATE',
                value: time(tag.date, 'D')
            })
            .addLocaleField({
                name: 'TAGS_LIST_SPECIFIC_USES',
                value: tag.uses.toString()
            });
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/commands/tags/list.ts
> +    const guild = interaction.guild.id;
```suggestion
    const guild = interaction.guildId;
```

2022-02-06 21:26 UTC, SuperchupuDev commented on src/commands/tags/list.ts
> +    if (tags.length === 0)
```suggestion
    if (!tags.length)
```

2022-02-06 21:32 UTC, xiboon approved these changes, later dismissed

2022-02-06 21:35 UTC, SuperchupuDev commented on src/commands/tags/delete.ts
> +        addComponents([
```suggestion
        .addComponents([
```
im stupid

2022-02-06 21:37 UTC, SuperchupuDev commented on src/components/tagList.ts
> +        .setLocaleTitle('TAGS_LIST_TITLE', { server: interaction.guild.name });
```suggestion
        .setLocaleTitle('TAGS_LIST_TITLE', { server: interaction.guild.name })
```
im stupid part 2

2022-02-06 22:09 UTC, SuperchupuDev requested changes
didnt notice this before

2022-02-06 22:09 UTC, SuperchupuDev commented on src/commands/tags/list.ts
> +        if (!resultArray[chunkIndex]) resultArray[chunkIndex] = [];
```suggestion
        resultArray[chunkIndex] ||= [];
```

2022-02-06 22:10 UTC, SuperchupuDev approved these changes

2022-02-07 07:24 UTC, xiboon approved these changes

2022-02-07 07:24 UTC, merged