better logging
Fluorinebot/fluorine pull request #87
Opened 2022-02-01 21:17 UTC by night-lake

this makes the logging in sync with interactions

might add  other things.

2022-02-01 21:21 UTC, xiboon approved these changes, later dismissed

2022-02-01 21:22 UTC, night-lake commented
perhaps i should also make `Logger` static?

2022-02-01 21:39 UTC, SuperchupuDev commented
> perhaps i should also make `Logger` static?

if it works +1 on that

2022-02-02 06:42 UTC, night-lake commented
> > perhaps i should also make `Logger` static?
> 
> if it works +1 on that

it  could work but you wouldnt be able to log with `FluorineClient#logger`

2022-02-02 07:15 UTC, night-lake commented
> > perhaps i should also make `Logger` static?
> 
> if it works +1 on that

alright impemented in 8adc6fe

2022-02-02 17:22 UTC, SuperchupuDev requested changes

2022-02-02 17:22 UTC, SuperchupuDev commented on src/classes/Client.ts
> +import exposedLoggerProps from './Logger';
```suggestion
import { Logger } from './Logger';
```

2022-02-02 17:22 UTC, SuperchupuDev commented on src/classes/Client.ts
> +    logger: typeof exposedLoggerProps;
```suggestion
    logger: typeof Logger;
```

2022-02-02 17:22 UTC, SuperchupuDev commented on src/classes/Client.ts
> +        this.logger = exposedLoggerProps;
```suggestion
        this.logger = Logger;
```

2022-02-02 17:22 UTC, SuperchupuDev commented on src/classes/Logger.ts
> +export default exposedLoggerProps;
```suggestion
```

2022-02-02 17:43 UTC, SuperchupuDev approved these changes

2022-02-02 17:49 UTC, xiboon approved these changes

2022-02-02 17:49 UTC, merged