tak
Fluorinebot/fluorine pull request #93
Opened 2022-02-06 22:18 UTC by ArsBeneMoriendi

2022-02-07 07:22 UTC, xiboon requested changes

2022-02-07 07:22 UTC, xiboon commented on i18n/en-US.json
> +    "HYPIXEL_NO_ARGS": "You need to provide a player! Correct usege: {{- command}} <player>",
```suggestion
    "HYPIXEL_NO_ARGS": "You need to provide a player! Correct usage: {{- command}} <player>",
```
epic fail

2022-02-07 07:23 UTC, xiboon approved these changes

2022-02-07 07:30 UTC, SuperchupuDev approved these changes

2022-02-07 08:32 UTC, merged

2022-02-07 08:33 UTC, night-lake requested changes
idk about the polish but yeah

2022-02-07 08:33 UTC, Nyameliaaaa commented on i18n/en-US.json
> +    "BAN_SUCCESS_DESCRIPTION": "Successfully banned the member!",
```suggestion
    "BAN_SUCCESS_DESCRIPTION": "Successfully banned that member!",
```

2022-02-07 08:33 UTC, night-lake commented on i18n/en-US.json
> +    "KICK_SUCCESS_DESCRIPTION": "Successfully kicked the member!",
```suggestion
    "KICK_SUCCESS_DESCRIPTION": "Successfully kicked that member!",
```

2022-02-07 08:33 UTC, night-lake commented on i18n/en-US.json
> +    "MUTE_SUCCESS_DESCRIPTION": "Succesfully muted the member!",
```suggestion
    "MUTE_SUCCESS_DESCRIPTION": "Succesfully muted that member!",
```

2022-02-07 08:33 UTC, night-lake commented on i18n/en-US.json
> +    "UNMUTE_SUCCESS_DESCRIPTION": "Succesfully unmuted the member!",
```suggestion
    "UNMUTE_SUCCESS_DESCRIPTION": "Succesfully unmuted that member!",
```

2022-02-07 08:33 UTC, Nyameliaaaa commented on i18n/en-US.json
> +    "WARN_SUCCESS_DESCRIPTION": "Successfully warned the member!",
```suggestion
    "WARN_SUCCESS_DESCRIPTION": "Successfully warned that member!",
```

2022-02-07 08:33 UTC, night-lake commented on i18n/en-US.json
> +    "AI_WAIT": "Added to queue! You're a number {{- queue}} in the queue",
```suggestion
    "AI_WAIT": "Added to queue! You're number {{- queue}} in the queue",
```

2022-02-07 08:34 UTC, night-lake commented
nvm im an idiot it got merged

2022-02-08 11:55 UTC, night-lake reviewed
sex

2022-05-05 13:49 UTC, luczoxz commented
penis