Update issue templates
Fluorinebot/fluorine pull request #99
Opened 2022-02-07 19:30 UTC by xiboon

lol

2022-02-07 19:50 UTC, SuperchupuDev requested changes

2022-02-07 19:50 UTC, SuperchupuDev commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: invalid
```suggestion
labels: bug
```

2022-02-08 08:14 UTC, night-lake approved these changes
i mean the only issues being made are ours but whatever.

2022-03-27 18:13 UTC, SuperchupuDev commented
superseded by #150

2022-03-27 18:13 UTC, closed without merging